# https://www.home-assistant.io/components/binary_sensor.ping/

homeassistant:
  customize:
    binary_sensor.modem:
      icon: mdi:router-wireless
    binary_sensor.router:
      icon: mdi:router-wireless
    binary_sensor.lenovo:
      icon: mdi:laptop-windows
    binary_sensor.philips:
      icon: mdi:router-wireless
    binary_sensor.ikea:
      icon: mdi:router-wireless
    binary_sensor.osram:
      icon: mdi:router-wireless

binary_sensor:
  - platform: ping
    host: !secret modem_ip
    name: Modem
    count: 2
    scan_interval: 60
  - platform: ping
    host: !secret router_ip
    name: Router
    count: 2
    scan_interval: 60
  - platform: ping
    host: !secret server_ip
    name: Filer
    count: 2
    scan_interval: 60
  - platform: ping
    host: !secret lenovo_ip
    name: Lenovo
    count: 2
    scan_interval: 60
  - platform: ping
    host: !secret hue_ip
    name: Philips
    count: 2
    scan_interval: 60
  - platform: ping
    host: !secret ikea_ip
    name: Ikea
    count: 2
    scan_interval: 60
  - platform: ping
    host: !secret lightify_ip
    name: Osram
    count: 2
    scan_interval: 60
