# https://www.home-assistant.io/components/sensor.speedtest/
# https://www.home-assistant.io/components/sensor.rest/
# https://github.com/andrey-git/home-assistant-custom-ui

homeassistant:
  customize:
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:arrow-down-bold-circle-outline
      templates:
        theme: >-
          var l = parseInt(entities['sensor.speedtest_download'].state); 
          if (l <= 40) { return 'card-critical'; }
          else if (l <= 60) {return 'card-warning' }
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:arrow-up-bold-circle-outline
      templates:
        theme: >-
          var l = parseInt(entities['sensor.speedtest_upload'].state); 
          if (l <= 6) { return 'card-critical'; }
          else if (l <= 10) {return 'card-warning' }
    sensor.speedtest_ping:
      friendly_name: Ping
      templates:
        theme: >-
          var l = parseInt(entities['sensor.speedtest_ping'].state); 
          if (l >= 25) { return 'card-critical'; }
          else if (l >= 22) {return 'card-warning' }
    sensor.external_ip:
      icon: mdi:wan
      show_last_changed: true

sensor:
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 3
      - 6
      - 9
      - 12
      - 15
      - 18
      - 21
    monitored_conditions:
      - ping
      - download
      - upload
    server_id: 17568
  - platform: rest
    resource: http://icanhazip.com
    name: External IP
