# https://www.home-assistant.io/components/sensor.time_date/
# https://www.home-assistant.io/components/sensor.worldclock/

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'time_utc'
  - platform: worldclock
    name: UK
    time_zone: Europe/London
  - platform: worldclock
    name: San Francisco
    time_zone: America/Los_Angeles
  - platform: template
    sensors:
      date:
        value_template: '{{ now().strftime("%d-%-m-%y") }}'

