- id: '1574092214876'
  alias: Sunset lights
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states.sun.sun.attributes.elevation | int < 8 }}'
  condition: []
  action:
  - data: {}
    entity_id: switch.kitchen_sink
    service: switch.turn_on
- id: '1574096809868'
  alias: Sunrise lights
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: all
    service: light.turn_off
  - data: {}
    entity_id: all
    service: switch.turn_off
- id: '1574278470479'
  alias: Notify when UPS goes on battery
  description: ''
  trigger:
  - entity_id: sensor.office_ups_status_data_short
    from: OL
    platform: state
    to: OB
  condition: []
  action:
  - data:
      message: Lost power @ {{ as_timestamp(now()) | timestamp_custom('%-I:%M%p %d-%b-%Y',
        true) }}
    service: notify.forwardcomputers
- id: '1574280082056'
  alias: Notify when UPS goes on online
  description: ''
  trigger:
  - entity_id: sensor.office_ups_status_data_short
    from: OB
    platform: state
    to: OL
  condition: []
  action:
  - data:
      message: Power's back @ {{ as_timestamp(now()) | timestamp_custom('%-I:%M%p
        %d-%b-%Y', true) }}
    service: notify.forwardcomputers
- id: '1574280193336'
  alias: Notify when UPS battery needs replacing
  description: ''
  trigger:
  - platform: template
    value_template: '{{ ''RB'' in states(''sensor.office_ups_status_data_short'')
      }}'
  condition: []
  action:
  - data:
      message: 'UPS battery must be replaced. Search on amazon: https://amzn.to/2wzV4Io
        and https://amzn.to/2MXBQH2'
    service: notify.forwardcomputers
- id: '1575054174712'
  alias: Vacation
  description: ''
  trigger:
  - at: 00:00:01
    platform: time
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      date: 15/2/2020
      name: Belize
      type: in
    service: python_script.date_countdown
- id: '1575216740437'
  alias: Download EC forecast
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  - minutes: '30'
    platform: time_pattern
  condition: []
  action:
  - service: shell_command.download_ec_forecast_toronto
- id: '1578970908730'
  alias: Speedtest @ startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: speedtestdotnet.speedtest
- id: '1595596049319'
  alias: Night
  description: ''
  trigger:
  - platform: webhook
    webhook_id: night
  condition: []
  action:
  - data:
      command: HOME
    entity_id: media_player.nvidia_shield
    service: androidtv.adb_command
  - data:
      command: SLEEP
    entity_id: media_player.nvidia_shield
    service: androidtv.adb_command
  - data: {}
    entity_id: light.desk
    service: light.turn_off
  - data: {}
    entity_id: light.office
    service: light.turn_off
  mode: single
