# https://www.home-assistant.io/components/sensor.speedtest/
# https://www.home-assistant.io/components/sensor.rest/
# https://github.com/andrey-git/home-assistant-custom-ui

homeassistant:
  customize:
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:arrow-down-bold-circle-outline
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:arrow-up-bold-circle-outline
    sensor.speedtest_ping:
      friendly_name: Ping
      templates:
    sensor.external_ip:
      icon: mdi:wan
      show_last_changed: true

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - download
    - ping
    - upload
  server_id: 17394

sensor:
  - platform: rest
    resource: http://icanhazip.com
    name: External IP
