version: 2.1

jobs:
  test:
    working_directory: /hass
    docker:
      - image: homeassistant/amd64-homeassistant
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            apk update && apk add make
            mv /hass/config /config
            make --directory=/config test

workflows:
  version: 2.1

  commit:
    jobs:
      - test:
          context: global

  nightly:
    triggers:
      - schedule:
          # Times are in UTC, this job is run
          # daily @ 14HRS = 9AM EST, 20HRS = 3PM EST
          cron: "0 14,20 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test:
         context: global
