# https://www.home-assistant.io/docs/configuration/customizing-devices/
# https://github.com/andrey-git/home-assistant-custom-ui

"*.*":
  custom_ui_state_card: state-card-custom-ui

"automation.*":
  hidden: true
