# https://www.home-assistant.io/components/history/

include:
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - climate.thermostat.attributes.current_temperature
    - sensor.ec_temperature
    - sensor.humidex
    - sensor.wind_chill
    - climate.thermostat.attributes.current_humidity
    - sensor.ec_relative_humidity
    - sensor.ec_uv_index
  domains:
    - sun
