# https://www.home-assistant.io/components/panel_iframe/

cockpit:
  title: Cockpit
  icon: mdi:stack-console
  url: !secret cockpit_url
glances:
  title: Glances
  icon: mdi:stack-exchange
  url: !secret glances_url
portainer:
  title: Portainer
  icon: mdi:docker
  url: !secret portainer_url
