# https://www.home-assistant.io/docs/automation/

- id: theme_normal
  alias: Normal theme at startup
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data_template:
        name: >-
          normal
