# https://www.home-assistant.io/lovelace/

title: Home Assistant

resources:
  - url: /customcards/lovelace/card-tools.js?track=true
    type: js
  - url: /customcards/lovelace/fold-entity-row.js?track=true
    type: js
  - url: /customcards/lovelace/layout-card.js?track=true
    type: js
  - url: /customcards/lovelace/monster-card.js?track=true
    type: js
  - url: /customcards/lovelace/slider-entity-row.js?track=true
    type: js
  - url: /customcards/lovelace/compact-custom-header.js?track=true
    type: module
  - url: /customcards/lovelace/custom-weather-card-chart.js?track=true
    type: module
  - url: /customcards/lovelace/secondaryinfo-entity-row.js?track=true
    type: module
  - url: /customcards/lovelace/simple-thermostat.js?track=true
    type: module
  - url: /customcards/lovelace/tracker-card.js?track=true
    type: module

views:
  - title: Home
    icon: mdi:home
    # panel: true
    cards:
      - type: custom:compact-custom-header
        dir: '/www/lovelace/'
        main_config: true
        header: true
        menu: show
        notification: show
        voice: hide
        options: show
        chevrons: true
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
        filter:
          include:
            - entity_id: "*toner_pct*"
              state: '< 25'
            - entity_id: "*drum_pct*"
              state: '< 25'
            - entity_id: "*kitchen_battery*"
              state: '< 25'
            - entity_id: "*tradfri_remote*"
              state: '< 25'
            - entity_id: "*tradfri_motion*"
              state: '< 25'
            - attributes:
                battery: '< 25'
            - attributes:
                battery_level: '< 25'
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.bedroom
          - light.hallway
          - type: custom:slider-entity-row
            entity: light.led
            toggle: true
          - type: custom:slider-entity-row
            entity: light.floor
            toggle: true
          - switch.kitchen
          - switch.desk
          - type: custom:slider-entity-row
            entity: light.office
            toggle: true
      - type: custom:simple-thermostat
        entity: climate.thermostat
        name: Climate
        hide:
          state: true
        sensors:
          - entity: sensor.indoor_humidity
            name: Indoor humidity
          - entity: sensor.ec_relative_humidity
            name: Outside humidity
          - entity: sensor.ec_temperature
            name: Outside temperature
          - entity: sensor.ec_feels_like
            name: Feels like
          - entity: sensor.ec_uv_index
            name: UV
          - entity: sensor.sunrise_time
            name: Sunrise
          - entity: sensor.sunset_time
            name: Sunset
#
  - title: Weather
    icon: mdi:weather-cloudy
    panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: 'custom:weather-card-chart'
          title: Weather
          weather: weather.openweathermap
        - type: entities
          show_header_toggle: false
          entities:
            - sensor.ec_current_summary
            - sensor.ec_1_summary
            - sensor.ec_2_summary
            - sensor.ec_3_summary
            - sensor.ec_4_summary
            - sensor.ec_5_summary
            - sensor.ec_6_summary
        - type: custom:compact-custom-header
#
  - title: Images
    icon: mdi:weather-windy
    panel: true
    cards:
      - type: custom:layout-card
        layout: horizontal
        column_num: 2
        cards:
          - type: iframe
            url: !secret windy_url
            aspect_ratio: 83%
          - type: picture-glance
            entities: []
            camera_image: camera.ec_radar
            aspect_ratio: 83%
          - type: picture-glance
            entities: []
            camera_image: camera.ec_jet_stream
            aspect_ratio: 83%
          - type: custom:compact-custom-header
#
  - title: Environment
    icon: mdi:earth
    panel: true
    cards:
      - type: horizontal-stack
        cards:
        - type: entities
          title: Environmental
          show_header_toggle: false
          entities:
            - sensor.pollen
            - sensor.flu
            - entity: sensor.aqhi_friendly
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.aqhi.state ]]"
            - sensor.cigarettes
            - entity: sensor.o3_friendly
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.o3.state ]] ppb"
            - entity: sensor.pm_friendly
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.pm.state ]] µg/m³"
            - entity: sensor.no2_friendly
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.no2.state ]] ppb"
            - entity: sensor.co_friendly
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.co.state ]] ppm"
            - entity: sensor.so2_friendly
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.so2.state ]] ppb"
        - type: entities
          title: Plectranthus scutellarioides (Coleus)
          show_header_toggle: false
          entities:
            - sensor.kitchen_conductivity
            - sensor.kitchen_light_intensity
            - sensor.kitchen_moisture
            - sensor.kitchen_temperature
        - type: custom:compact-custom-header
#
  - type: vertical-stack
    title: Rooms
    icon: mdi:checkbox-multiple-blank-outline
    cards:
      - type: entities
        title: Livingroom
        entities:
          - light.led
          - light.floor
          - entity: remote.livingroom
            name: Harmony hub
          - entity: media_player.livingroom_tv
            name: Panasonic TV
          - entity: media_player.shield
            name: nVidia Shield
          - entity: media_player.livingroom_apple_tv
            name: Apple TV
          - entity: remote.livingroom_apple_tv
            name: Apple TV remote
      - type: entities
        title: Bedroom
        entities:
          - light.bedroom_left
          - light.bedroom_right
          - sensor.tradfri_remote_control
      - type: entities
        title: Office
        entities:
          - switch.desk
          - light.office
          - entity: media_player.office_tv
            name: Samsung TV
          - entity: media_player.office_speaker
            name: Google Home Mini
      - type: entities
        title: Hallway
        entities:
          - light.hallway_center
          - light.hallway_door
          - light.hallway_kitchen
          - sensor.tradfri_motion_sensor
      - type: entities
        title: Kitchen
        entities:
          - switch.kitchen
          - sensor.kitchen_battery
      - type: custom:compact-custom-header
#
  - title: Radio
    icon: mdi:play-circle-outline
    cards:
      - type: entities
        title: Radio
        show_header_toggle: false
        entities:
          - input_select.radio_speaker
          - input_select.radio_station
          - input_number.radio_volume
          - input_boolean.radio_onoff
      - type: custom:compact-custom-header
#
  - title: Devices
    icon: mdi:server
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        column_num: 3
        cards:
          - type: entities
            title: NAS
            show_header_toggle: false
            entities:
              - sensor.model_name
              - sensor.serial_number
              - sensor.cpu_load_total
              - sensor.memory_usage_real
              - sensor.volume_used_volume_1
              - sensor.status_volume_1
              - sensor.status_smart_sda
              - sensor.status_smart_sdb
          - break
          - type: entities
            title: Printer
            show_header_toggle: false
            entities:
              - sensor.printer_name
              - sensor.printer_serial
              - sensor.printer_firmware
              - sensor.printer_status
              - entity: sensor.printer_toner_pct_remain
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ sensor.printer_toner_page_remain.state ]] pages remaining"
              - entity: sensor.printer_drum_pct_remain
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ sensor.printer_drum_page_remain.state ]] pages remaining"
              - script.cleaning_mode
          - type: entities
            title: ISP
            show_header_toggle: false
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_upload
              - sensor.speedtest_ping
          - break
          - type: entities
            title: UPS
            show_header_toggle: false
            entities:
              - sensor.office_ups_model
              - sensor.office_ups_serial_number
              - sensor.office_ups_status
              - sensor.office_ups_load
              - sensor.office_ups_battery_runtime_mins
              - sensor.office_ups_battery_charge
          - type: entities
            title: Web Links
            show_header_toggle: false
            entities:
              - type: weblink
                name: Modem
                url: !secret modem_url
                icon: mdi:router-wireless
              - type: weblink
                name: Router
                url: !secret router_url
                icon: mdi:router-wireless
              - type: weblink
                name: Filer
                url: !secret filer_url
                icon: mdi:server-network
              - type: weblink
                name: Laser
                url: !secret laser_url
                icon: mdi:printer
              - type: weblink
                name: Powerline
                url: !secret powerliving_url
                icon: mdi:router-wireless
          - type: custom:compact-custom-header
#
  - title: HASS
    icon: mdi:home-assistant
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        column_num: 3
        cards:
          - type: entities
            title: Server
            show_header_toggle: false
            entities:
              - sensor.sys_name
              - entity: sensor.sys_current_firmware
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "[[ sensor.sys_latest_firmware ]]"
              - sensor.glances_total
              - sensor.glances_cpu_temp
              - sensor.processor_use
              - sensor.glances_ram_used
              - sensor.glances_disk_used
              - sensor.glances_swap_used
              - sensor.last_boot
          - break
          - type: entities
            title: OS
            show_header_toggle: false
            entities:
              - sensor.os
              - sensor.distro
              - sensor.kernel_version
          - type: entities
            title: Docker
            show_header_toggle: false
            entities:
              - sensor.docker_version
              - sensor.glances_containers_active
          - type: entities
            title: Home Assistant
            show_header_toggle: false
            entities:
              - entity: sensor.installed_version
                type: "custom:secondaryinfo-entity-row"
                secondary_info: "GitHub [[ sensor.github_version.state ]] - PyPi [[ sensor.pypi_version.state ]] - Docker [[ sensor.docker_version.state ]]"
              - sensor.uptime
          - break
          - type: custom:tracker-card
            title:
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker
          - type: custom:compact-custom-header
#
  - title: Debug
    icon: mdi:bug
    cards:
      - type: custom:monster-card
        card:
          type: glance
        filter:
          include: [{}]
      - type: custom:compact-custom-header
