# https://www.home-assistant.io/components/camera/

# Radar of Jet Stream
- platform: generic
  name: EC jet stream
  content_type: image/gif
  scan_interval: 10800
  still_image_url: http://weather.gc.ca/data/jet_stream/tempmapwx_e.gif
# Radar of surrounding rain or snow conditions
- platform: generic
  name: EC radar
  content_type: image/gif
  scan_interval: 900
  still_image_url: >-
    {% set delta = 10 %}
    {% set time = states('sensor.time') %}
    {% set location = states('sensor.environment_canada_radar') %}
    {% set offset = delta * 60 %}
    {% set timestamp = as_timestamp(utcnow()) - offset %}
    {% set minutes = ((timestamp | timestamp_custom('%M', false)) | int / 10) | int | string + '0' %}
    {% set datestamp = timestamp | timestamp_custom('%Y%m%d%H', false) + minutes %}
    {% set month = timestamp | timestamp_custom('%-m', false) | int %}
    {% if 4 <= month <= 10 %}
        {% set season = 'RAIN' %}
    {% else %}
        {% set season = 'SNOW' %}
    {% endif %}
    http://dd.weather.gc.ca/radar/PRECIPET/GIF/{{location}}/{{datestamp}}_{{location}}_PRECIPET_{{season}}.gif
# Toronto downtown camera
- platform: generic
  name: Toronto Downtown Camera
  scan_interval: 600
  still_image_url: http://www.metcam.navcanada.ca/dawc_images/wxcam/CYTZ/CYTZ_E-full-e.jpeg
