#!/usr/local/bin/python3

import requests
import re

#url = requests.get('https://downloadcenter.intel.com/product/122495/Intel-NUC-Kit-NUC7i3DNKE')
#url = requests.get('https://www.intel.com/content/www/us/en/products/sku/122495/intel-nuc-kit-nuc7i3dnke/downloads.html')
url = requests.get('https://www.intel.com/content/www/us/en/download/19137/bios-update-dnkbli30.html')
if url:
    part = re.search('<a href="(.+?)">BIOS Update', url.text).group(1)
else:
    raise SystemExit('0')
if part:
    nuc_url = ''.join(['https://downloadcenter.intel.com', part])
else:
    raise SystemExit('0')

url = requests.get(nuc_url)
if url:
    part = re.search('<meta name="DownloadVersion" content="(.+?)" />', url.text).group(1)
else:
    raise SystemExit('0')

print(part)
