#!/usr/local/bin/python3

from bs4 import BeautifulSoup
import requests

url = requests.get('https://www.intel.com/content/www/us/en/download/18838/bios-update-bnkbl357.html')
if url:
    soup = BeautifulSoup(url.text, 'html.parser')
    version = soup.find('meta', attrs={'name':'DownloadVersion'})
    print(version['content'])
else:
    raise SystemExit('0')

